# ===================================================================================================
# ===  bmilcs docker compose  =======================================================================
# ===================================================================================================

#https://bitwarden.com/#download
# curl -Lso bitwarden.sh https://go.btwrdn.co/bw-sh \
#   && chmod +x bitwarden.sh
# ./bitwarden.sh install
# ./bitwarden.sh start

version: '3.3'

services:

  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  #https://hub.docker.com/r/containrrr/watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PGID
      - PUID
      - TZ
    command: --schedule "0 0 6 * * *" --label-enable --cleanup
    restart: unless-stopped
    
  #https://hub.docker.com/r/linuxserver/hydra2
  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    hostname: hyd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONFIG}/hydra2:/config
      - ${DOWNLOAD}:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped

  #https://hub.docker.com/r/linuxserver/jackett/
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    hostname: jac
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    # - RUN_OPTS=run options here #optional
    volumes:
      - ${CONFIG}/jackett:/config
      - ${DOWNLOAD}/watch:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  #https://hub.docker.com/r/linuxserver/sabnzbd
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    hostname: sab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONFIG}/sabnzbd:/config
      - ${DOWNLOAD}/watch:/watch
      - ${DOWNLOAD}/complete:/downloads
      - ${DOWNLOAD}/temp:/incomplete-downloads #optional
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped

  #https://hub.docker.com/r/linuxserver/rutorrent
    rutorrent:
      image: linuxserver/rutorrent
      container_name: rutorrent
      hostname: tor
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
        - ${CONFIG}/rutorrent:/config
        - ${DOWNLOAD}:/downloads
      ports:
        - 80:80
        - 5000:5000
        - 51413:51413
        - 6881:6881/udp
      restart: unless-stopped

  #https://hub.docker.com/r/cpoppema/docker-flexget/
  flexget:
    image: cpoppema/docker-flexget
    container_name: flexget
    hostname: flex
    ports:
      - "5050:5050"
    volumes:
      - ${CONFIG}/flexget:/config
      - ${MEDIA}/podcasts:/podcasts  # - ${MEDIA}/watch:/watch
    environment:
      - PGID
      - PUID
    restart: unless-stopped

  #https://hub.docker.com/r/linuxserver/lidarr
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    hostname: lid
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ${CONFIG}/lidarr:/config
      - ${MEDIA}/music:/music
      - ${DOWNLOAD}:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
      
   
# https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: son
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    - UMASK_SET=022 #optional
    volumes:
    - ${CONFIG}/sonarr:/config
    - ${MEDIA}/tv:/tv
    - ${DOWNLOAD}:/downloads
    ports:
    - 8989:8989
    restart: unless-stopped

#https://hub.docker.com/r/linuxserver/radarr/
  ---
  version: "2"
  services:
    radarr:
      image: linuxserver/radarr
      container_name: radarr
      hostname: rad
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - UMASK_SET=022 #optional
      volumes:
        - ${CONFIG}/radarr:/config
        - ${MEDIA}/movies:/movies
        - ${DOWNLOAD}:/downloads
      ports:
        - 7878:7878
      restart: unless-stopped

# #https://hub.docker.com/r/linuxserver/tautulli
#   tautulli:
#     image: linuxserver/tautulli
#     container_name: tautulli
#     hostname: tau
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=Europe/London
#     volumes:
#       - ${CONFIG}/tautulli:/config
#       - path to plex logs:/logs
#     ports:
#       - 8181:8181
#     restart: unless-stopped

  #https://hub.docker.com/r/linuxserver/ombi/
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - BASE_URL=/ombi #optional
    volumes:
      - ${CONFIG}/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  #https://hub.docker.com/r/linuxserver/bazarr
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    hostname: baz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ${CONFIG}/bazaar:/config
      - ${MEDIA}/movies:/movies
      - ${MEDIA}/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  #https://hub.docker.com/r/linuxserver/heimdall/
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    hostname: heim
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONFIG}/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  portainer:
    image: portainer/portainer
    hostname: portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA}/portainer:/data
